repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8   # Use the latest Ruff version
    hooks:
      - id: ruff
        args: ["--fix"]     # Auto-fix lint issues
      - id: ruff-format     # Format code (like Black)
        